# Generated by Django 3.2.13 on 2022-11-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='casetag',
            field=models.ManyToManyField(related_name='movies', to='movies.CaseTag'),
        ),
        migrations.AddField(
            model_name='movie',
            name='moodtag',
            field=models.ManyToManyField(related_name='movies', to='movies.MoodTag'),
        ),
    ]
